# Generated by Django 4.1 on 2022-10-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='author',
        ),
    ]
