# Generated by Django 4.1 on 2022-11-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgethistory',
            name='totalAmount',
            field=models.IntegerField(null=True),
        ),
    ]
